## Numpy

**Numpy** est une librairie permettant de manipuler les tableaux et les matrices de nombres de manière très performante dans l'environnement Python.

In [1]:
import numpy as np

## Tableaux

La fonction **array()** permet d'initialiser un **tableau Numpy** monodimensionnel à partir d'une liste simple, ou un tableau Numpy multidimensionnel à partir d'une liste de listes :

In [2]:
tab1 = np.array([1,2,3])
tab1

array([1, 2, 3])

In [3]:
tab2 = np.array([[1,2,3],[4,5,6]])
tab2

array([[1, 2, 3],
       [4, 5, 6]])

La fonction **arange()** permet d'initialiser le contenu d'un tableau avec des valeurs consécutives (valeur départ incluse, valeur arrivée exclue, pas) :

In [4]:
tab3 = np.arange(0,10,2)
tab3

array([0, 2, 4, 6, 8])

La fonction **linspace()** permet d'initialiser le contenu d'un tableau avec des valeur espacées de manière égale dans un intervalle donné (valeur début intervalle, valeur fin intervalle, nombre de valeurs à générer) :

In [5]:
tab4 = np.linspace(0,10,9)
tab4

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

Numpy définit une série de fonctions pour initialiser des tableaux ou matrices remarquables :

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.diag([2,3,4])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [10]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

La fonction **random.randint()** permet de créer un tableau rempli de nombres entiers aléatoires (valeur min, valeur max, dimensions) :

In [11]:
np.random.randint(0, 100, (2,3))

array([[22, 18,  1],
       [21, 80,  2]])

La propriété **shape** d'un tableau numpy permet de vérifier les dimensions du tableau : (nombre de lignes, nombre de colonnes).

In [12]:
tab2.shape

(2, 3)

La fonction **reshape()** permet de réarranger différemment les valeurs contenues dans le tableau (nombre de lignes cible, nombre de colonnes cible) :

In [13]:
tab5 = tab4.reshape(3,3)

print(tab4)
print("---")
print(tab5)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]
---
[[ 0.    1.25  2.5 ]
 [ 3.75  5.    6.25]
 [ 7.5   8.75 10.  ]]


On voit qu'un nouveau tableau est retourné, mais que le tableau initial n'est pas modifié.

La fonction **resize()** permet de modifier directement le tableau en place :

In [14]:
tab4.resize(3,3)

tab4

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

Les fonctions **vstack() et hstack()** permettent d'assembler une liste de tableaux pour former un tableau résultat unique en les superposant verticalement, ou en les les positionnant l'une à côté de l'autre :

In [15]:
o = np.ones((2,3),int)

print(np.vstack([o, 2*o]))
print("---")
print(np.hstack([o, 2*o]))

[[1 1 1]
 [1 1 1]
 [2 2 2]
 [2 2 2]]
---
[[1 1 1 2 2 2]
 [1 1 1 2 2 2]]


## Opérations sur les tableaux

Les **opérations arithmétiques** appliquées sur deux tableaux de même taille sont répétées élément par élément pour chacune des valeurs contenues dans les tableaux :

In [16]:
tab1 = np.array([1,2,3])
tab2 = np.array([4,5,6])

print(tab1 + tab2)
print(tab1 - tab2)
print(tab1 * tab2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


Même comportement pour les opérations arithmétiques entre un tableau et un nombre :

In [17]:
print(tab1 + 10)
print(tab1 * 5)
print(tab1 ** 2)

[11 12 13]
[ 5 10 15]
[1 4 9]


La propriété **T** permet d'accéder au tableau **transposé** (effet miroir sur les différentes dimensions) :

In [18]:
tab3 = np.vstack([tab1,tab2])
print(tab3)
print("---")

print(tab3.T)

[[1 2 3]
 [4 5 6]]
---
[[1 4]
 [2 5]
 [3 6]]


La propriété **dtype** permet de vérifier le type de données stockées dans un tableau Numpy.

La fonction **astype()** permet de modifier le type de données stocké dans un tableau Numpy.

In [19]:
print(tab3.dtype)
print(tab3)
print("---")

tab3 = tab3.astype("f")
print(tab3.dtype)
print(tab3)

int32
[[1 2 3]
 [4 5 6]]
---
float32
[[1. 2. 3.]
 [4. 5. 6.]]


Numpy définit des **fonctions d'agrégation** appliquées aux valeurs contenues dans un tableau (min(), max(), mean() ...) :

In [20]:
tab3.min()

1.0

In [21]:
# index de la plus petite valeur dans le tableau
tab3.argmin()

0

In [22]:
tab3.max()

6.0

In [23]:
# index de la plus grande valeur dans le tableau
tab3.argmax()

5

In [24]:
# moyenne
tab3.mean()

3.5

In [25]:
# écart type
tab3.std()

1.7078252

In [26]:
tab3.sum()

21.0

## Accès aux éléments des tableaux

On peut extraire des valeurs ou des fragments de tableaux Numpy avec la même syntaxe que pour une liste :

In [27]:
tab1[2]

3

In [28]:
print(tab3[1])
print("---")
print(tab3[1,0])

[4. 5. 6.]
---
4.0


In [29]:
tab7 = np.arange(1,20,2)
tab7

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [30]:
tab7[:3]

array([1, 3, 5])

In [31]:
tab7[-3:]

array([15, 17, 19])

In [32]:
tab7[3:8]

array([ 7,  9, 11, 13, 15])

In [33]:
tab8 = np.arange(25)
tab8.resize((5,5))
tab8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
tab8[1:4,-3:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

On peut aussi sélectionner des éléments du tableau (en lecture ou en écriture) avec une condition spécifiée entre les crochets, dans laquelle le nom du tableau représente une valeur :

In [35]:
tab8[tab8 > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
tab8[tab8 > 20] = 0
tab8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20,  0,  0,  0,  0]])

On voit dans ce dernier exemple que le fragment de tableau extrait par indexing ou slicing est en fait une **vue partielle sur le contenu du tableau original** : toute modification appliquée au fragment de tableau renvoyé est en fait appliquée au tableau complet original.

La fonction **copy()** permet de dupliquer les données d'un tableau original dans un nouveau tableau, qui peut alors être modifié sans risquer d'impacter le tableau original.

In [37]:
tab9 = np.arange(1,11)
print(tab9)

tab9_fragment = tab9[3:8]
tab9_fragment[0] = 0
print(tab9)

tab9_fragment_copy = tab9_fragment.copy()
tab9_fragment_copy[0] = 99
print(tab9)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  0  5  6  7  8  9 10]
[ 1  2  3  0  5  6  7  8  9 10]


On peut parcourir les éléments d'un tableau dans une boucle for :
- on accède d'abord aux lignes
- puis on peut parcour les éléments de la ligne
- la fonction **enumerate** permet d'accéder simultanément à l'index de l'élément et à l'élément lui-même

In [38]:
tab10 = np.arange(1,10)
tab10.resize((2,4))
tab10

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
for ligne in tab10:
    print(ligne)

[1 2 3 4]
[5 6 7 8]


In [40]:
for ligne in tab10:
    for valeur in ligne:
        print(valeur)

1
2
3
4
5
6
7
8


In [41]:
for i,ligne in enumerate(tab10):
        print("ligne ",i," : ",ligne)

ligne  0  :  [1 2 3 4]
ligne  1  :  [5 6 7 8]


La fonction **zip()** permet de parcourir deux tableaux en parallèle :

In [42]:
print(tab1)
print(tab2)

[1 2 3]
[4 5 6]


In [43]:
for val1,val2 in zip(tab1,tab2):
    print(val1," --- ",val2)

1  ---  4
2  ---  5
3  ---  6
